### PR TITLE
Cosmetic cleanup of CHANGELOG.md

### PR DESCRIPTION
**Pull request by csbnw**
**Description**

The `CHANGELOG.md` had some inconsistencies and other minor cosmetic things that could be improved. This PR addresses those.

**Related issues**:

- N.A.

### CODE REVIEW

**Review by loostrum — CHANGES_REQUESTED** [review]
The updated version looks good! Perhaps you can address the few issues raised by Codacy about blank lines surrounding lists, and then it's good to merge I'd say

**Comment by csbnw** [comment]
> The updated version looks good! Perhaps you can address the few issues raised by Codacy about blank lines surrounding lists, and then it's good to merge I'd say

To be honest, I don't quite understand Codacy's suggestions. On some occasions it seems to prefer empty lines and on some others it doesn't give a hint. Should we have an empty line after every "Changed"/"Added"/"Removed" line?

**Comment by csbnw** [comment]
I have added `mdformat` to the pre-commit configuration to automatically format the `CHANGELOG.md`. For now only this file is checked, since fixing the formatting of the other markdown files is outside the scope of this MR.

**Review by loostrum — APPROVED** [review]
`mdformat` looks like a very useful addition, and I see that codacy is happy as well now.

**Pull request merged**
