### PR TITLE
Add instructions to set up self-hosted runners on DAS and a dedicated server

### PR DESCRIPTION
**Pull request by abelsiqueira**
**Description**

cc @csbnw

This pull request ~~adds~~ explains how to use a workflow that mimics a DAS user using VPN and SSH to log in and run a job on the GPU.
The process to set it up involves obtaining an OpenVPN configuration file and SSH credentials and storing this information on the GitHub secrets page. See the changes on README.dev.md for more details.

_I did not set up this information for this repository, but I did for a test project https://github.com/abelsiqueira/test-das._

**Notice:** I do not guarantee that this is not against DAS usage.

**Security concerns**

- :warning:  Since this touches VPN and SSH, anyone with access to this repository can run (non-privileged) code on DAS.
- :heavy_check_mark: The secrets themselves can never be retrieved again, not even by the creator.
- :heavy_check_mark: The secrets are not available to forks, so even if someone modifies the action, they don't have access to the credentials.

The workflow files are available here: https://gist.github.com/abelsiqueira/3e5e7a8308bb8f41f677033ebd9c61ac

**Related issues**:

- #25 

**Instructions to review the pull request**

There is no easy way to review this pull request. Check online if everything makes sense. You can also look at https://github.com/abelsiqueira/test-das/ for a live example.

### CODE REVIEW

**Comment by csbnw** [comment]
ASTRON currently does not have an eduVPN subscription, so I cannot test this, unfortunately.
I am not sure whether it is a good idea to install (and have to manage) a dedicated OpenVPN server on DAS-5/6 for this purpose.
@svlugt , @john-romein , what are your thoughts on this?

**Comment by abelsiqueira** [comment]
I think you have some kind of VPN, though. I have found this: https://vpn.astron.nl/remote/login?lang=en

**Comment by csbnw** [comment]
> I think you have some kind of VPN, though. I have found this: https://vpn.astron.nl/remote/login?lang=en

This VPN is intended to access some ASTRON services, you can not access DAS from there.

**Comment by abelsiqueira** [comment]
As per @fdiblen's suggestion, I remove the workflow files. They can be found through the gist link in the description.

**Comment by fdiblen** [comment]
We will extend this PR by adding a second option "running CI on a dedicated server". We will then ask for review of the other contributors.

**Comment by bouweandela** [comment]
We discussed this at a meeting today with @csbnw @loostrum @laurasootes and @bouweandela and decided to close this pull request for now because of the security issue.

**Pull request closed without merging**
